### ISSUE TITLE
Missing dev dependency for initial built

### ISSUE THREAD

**Issue by HerzogIgzorn** [SAP-samples/ui5-typescript-walkthrough#69]
As mentioned [here](https://github.com/SAP-samples/ui5-typescript-walkthrough/blob/fc329826ccc0ba09cb32530708d82859ebf7218f/steps/02/README.md?plain=1#L223), during initial serve, the UI5 build is performed. Unfortunately, I ended up with an error:

Failed to load task repository. Missing dependency to '@ui5/builder'? Error: Cannot find package '@ui5/builder' imported from C:\Users\sebastian.bender@sap.com\git\ui5-walkthrough-ts\node_modules\@ui5\project\lib\graph\ProjectGraph.js

`npm i -D @ui5/builder` solved the issue but this is not mentioned in the tutorial step 2.

**Comment by petermuessig** [comment]
This is an issue of the `ui5-middleware-serveframework` and will be fixed with the cross-linked PR which closes the issue.
